//MESSAGES ACTION TYPES;
export const ADD_MESSAGE = "ADD_MESSAGE";
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const MESSAGE_HISTORY = "MESSAGE_HISTORY";

//USER ACTION TYPES;
export const ADD_USER_NAME = "ADD_USER_NAME";

